### ISSUE TITLE
Add support for plotting using incanter

### ISSUE THREAD

**Issue by maximilianigl** [jasongilman/proto-repl#101]
Hi,

as incanter's plotting capabilities seem to be greater than proto-repl-chart's, integration for it would be great.
For example, I couldn't find the corresponding possibility in proto-repl-chart to do something like xy-plot in incanter (see screenshot).
![screen shot 2016-05-07 at 17 44 08](https://cloud.githubusercontent.com/assets/4333579/15093304/6b608db6-147b-11e6-875e-2cb9257f4e79.png)

Would it be e.g. possible to do so by implementing a proto-repl version of incanter's `view` function or are there problems associated to that?

**Comment by jasongilman** [comment]
I like the idea of doing this in Proto REPL Charts. I've wanted this myself. I couldn't really integrate the visual parts of Incanter because it relies on viewing things using Java and Swing which isn't compatible with Atom's browser based visualizations. However you can certainly use Incanter from Proto REPL. It will just display in a separate window. I'd still like to add this to Proto REPL charts with a simple API. I like the ability to have these visualizations built into the editor and REPL.

**Comment by jasongilman** [comment]
Since incanter already works from Proto REPL (just not displaying inside Atom) I'm going to close this issue.
