### ISSUE TITLE
Defining symbols under a (ns foo) declaration defines them in the `user` namespace

### ISSUE THREAD

**Issue by WalterGR** [jasongilman/proto-repl#114]
I'm using proto-repl 1.1.11 in Atom 1.8.0.

I have a file like this in a Leiningen project:

```
(ns waltergr.test)
(def one 1)
```

If I evaluate the `def` line, the following is displayed to the REPL.

```
(def one 1)
user=> #'user/one
```

Further:

```
waltergr.test/one
user=> CompilerException java.lang.ClassNotFoundException: waltergr.test, compiling:(/private/var/folders/4x/9jdwhngn4g9gmsc8s0l3ys580000gn/T/form-init1436554472165199566.clj:1:1) 

(resolve 'one)
user=> #'user/one
```

Is that the expected behavior?

(I assumed, perhaps incorrectly, that `Repl.executeCodeInNs` looks for a namespace declaration and evaluates code in the context of that namespace.  Adding logging code to proto-repl shows that the namespace declaration is found properly...)

**Comment by jasongilman** [comment]
I think the problem is that the namespace has not yet been defined. Proto REPL won't create the namespace if it doesn't exist. If you evaluate the namespace declaration it should work. Proto REPL is kind of an intermediary between your code in Atom and the code in the JVM. Proto REPL sends the code you tell it to to the JVM. The JVM doesn't know about that namespace yet so that's why you see the error. 

When evaluating a block of code it sends the namespace to the JVM and if it doesn't exist will default to whatever namespace is currently set in the REPL. That's why you see `#'user/one`

**Comment by WalterGR** [comment]
That makes sense.  Thanks.  Closing.
