### ISSUE TITLE
starting REPL with a specific settings from project.cljs 

### ISSUE THREAD

**Issue by ItamarShDev** [jasongilman/proto-repl#119]
Maybe I've missed it, but is there any way to set the repl to run an already set environment from project.cljs?
i have prod, test, and dev. once i run repl in proto-repl, I want to be able to tell it to run prod for example

**Comment by jasongilman** [comment]
You can do that in the Proto REPL settings. Try changing it to `with-profile +test repl :headless` The plus is needed so that the regular repl settings will still be available. If you need more information you can also check out the leiningen documentation. 

<img width="775" alt="settings_ __users_jason_work_github_workspace_proto-repl-charts" src="https://cloud.githubusercontent.com/assets/192983/16750281/afe235c4-479e-11e6-9225-b122f8c89e68.png">

**Comment by ItamarShDev** [comment]
Thanks

**Comment by ItamarShDev** [comment]
I was referring more to a shortcut to a specific run
and not to replace the defaults
