### ISSUE TITLE
Error starting REPL on Windows

### ISSUE THREAD

**Issue by jcomplex** [jasongilman/proto-repl#13]
I have installed this package in Atom running in Windows.  I can successfully in my terminal type lein repl and the repl server starts and I can code from there.  But when I open Clojure REPL in Atom I keep getting:

Error starting repl: Error: spawn lein ENOENT
You may need to configure the lein path in proto-repl settings

REPL Closed

I have set my lein path as: C:\Users\joyaj.lein\bin\lein.bat

Is this incorrect?

**Comment by jasongilman** [comment]
What happens when you type "C:\Users\joyaj.lein\bin\lein.bat repl" in a terminal? If that works "C:\Users\joyaj.lein\bin\lein.bat" should be the right thing to put in the settings for Lein Path. It could be that you need to configure it as "C:\Users\joyaj.lein\bin\lein" in Proto REPL

**Comment by jcomplex** [comment]
When I type `lein repl` in my cmd terminal I can run my clojure test project just fine.  But no dice in Atom.  I notice there is also someone else with this same issue on [StackOverflow](http://stackoverflow.com/questions/34117908/error-spawn-lein-enoent-in-atom-proto-repl-on-windows) .  

I ran `which lein` and got back: `C:\Users\joyaj\.lein\bin\lein.bat`

I have tried to put it in:
- `C:\Users\joyaj\.lein\bin\lein` - Does not work
- `lein` - Does not work
- `C:\Users\joyaj\.lein` - Does not work
- `C:\Users\joyaj\.lein\bin` - How it is set in my path variable and also does not work
- `C:\Users\joyaj\.lein\bin\lein.bat` - Does not work

This is slightly frustrating as I would love to use this package very much.

**Comment by jasongilman** [comment]
I don't have access to a Windows PC right now which makes it hard to debug. I did some research and it looks like Node.js has a 4 year old issue with spawning processes on Windows that are .bat or similar. https://github.com/nodejs/node-v0.x-archive/issues/2318 

I found potential work arounds and fixes for code:
- http://matthew-jackson.com/notes/development/node-child_process-enoent-error-windows/
- https://github.com/bower/bower/issues/626

Its going to be at least a few days before I can try these out on a Windows PC. Since you have this all ready to go maybe you could try it?

If so here are the instructions:
1. Set the Lein Path configuration in Atom to "C:\Users\joyaj.lein\bin\lein.bat".

The next part requires modifying the code in Proto REPL.
1. Open C:\Users\joyaj.atom\packages\proto-repl\lib\repl-process.coffee (I think that's the location on windows)
   On line 18 change `"lein"` to `"lein.bat"`.
2. Restart Atom and then see if the REPL will start.

If that doesn't work there's a solution referred to in the bower link above (https://github.com/bower/bower/issues/626) that may work. I don't know exactly what the code would look like that does that yet.

**Comment by kimoin** [comment]
I had the same problem but got it working for me. In addition to "lein.bat" I had to set path separator to semicolon on line 15.

**Comment by jasongilman** [comment]
Thanks for the information. I'm making the fixes now and I'm going to push a new version.

**Comment by austincrft** [comment]
I am still experiencing this issue on Windows.

Lein Path:
`C:\ProgramData\chocolatey\bin\lein.bat`

`C:\ProgramData\chocolatey\bin\lein.bat repl` from the project directory works.

I've validated in the `config.cson` that the path is getting properly escaped, but I still get this error:

```
Starting REPL in C:\src\clj-webapp
Error starting repl: Error: spawn lein.bat ENOENT
You may need to configure the lein path in proto-repl settings

REPL Closed
--------------------
```

Any advice?

**Comment by jasongilman** [comment]
I haven't tested Proto REPL on Windows yet. I'm going to get a Windows VM and make sure everything is working. There's an open pull request right now https://github.com/jasongilman/proto-repl/pull/49 that may fix some things for Windows. You could try manually applying the changes locally to see if they fix your issues.

**Comment by jasongilman** [comment]
Reopening this issue until I verify all the Windows problems are resolved.

**Comment by jasongilman** [comment]
I got the same error on windows VM. I was able to fix it so it worked on Windows now. Please let me know if you see any more windows problems.

**Comment by pythys** [comment]
Strangely, I'm facing this issue on Linux!  Lein is not in a standard location, I put it in /opt/leiningen. All variations of lein, /opt/leiningen/lein, /opt/leiningen are not working for some reason with the same above error message.

**Comment by jasongilman** [comment]
What do you have configured in Proto REPL?  What's the error message you're seeing?

**Comment by pythys** [comment]
I figured out what the reason is after a little bit of debugging. The logic removes the word matching "lein" and my directory is /opt/leiningen which translates to /optingen. I hardcoded the path.

This is a genuine bug though. The parsing code is brittle and should be done in a cleaner way to avoid such corner cases.

**Comment by jasongilman** [comment]
That's a good find. I'll file a new issue for this and fix it.

**Comment by bcambel** [comment]
I am also having this issue in MacOSX

**Comment by rkwofford** [comment]
Likewise on Windows: "The system cannot find the path specified."

**Comment by ryancole** [comment]
> Likewise on Windows: "The system cannot find the path specified."

@rkwofford I believe the config value should just be the directory, not an absolute path to the `lein.bat`. I've got mine configured as just the directory and it's working.

**Comment by pythys** [comment]
@ryancole nope, even a pure directory does not work if the directory name has the characters "lein" in it

**Comment by ryancole** [comment]
Not the case. I had my bat file in a directory named leiningen. Worked fine.

**Comment by pythys** [comment]
@ryancole hmmm then pehaps the parsing is OS specific, I didn't look thoroughly at the code

**Comment by pedro-w** [comment]
It is platform specific - see [here](https://github.com/jasongilman/proto-repl/blob/master/lib/process/lein-runner.coffee#L30). Looks like 'lein.bat' is added if the path doesn't already end in 'lein.bat', for Windows.

**Comment by agrison** [comment]
I had the same problem on Mac, but I was using a path with a tilde. I changed it to a complete path and it worked great instantly.

So instead of `~/dev/tools/lein/lein` I had to specify `/Users/alex/dev/tools/lein/lein` in the proto-repl settings pane.

Thanks for the hard work everyone 👍

**Comment by dunefox** [comment]
I can't run any code because I get this error:

'exec' is not a task. See 'lein help'.
Did you mean this?
         new
         check

This works fine:
        C:\Users\Harkonnen>    where lein
        C:\Users\Harkonnen\.lein\bin\lein.bat

        C:\Users\Harkonnen>    C:\Users\Harkonnen\.lein\bin\lein.bat repl

My Path in 'lein' is: C:\Users\Harkonnen\.lein\bin\lein.bat
Standard Arguments (lein :headless)
OS is Windows 10

Do you have any idea why this is? It seems like the arguments aren't passed to the lein file.

**Comment by pacoescriba** [comment]
Finally, I removed completely leiningen and I reinstalled it in another directory, without "lein" in the path...

**Comment by memoryshuffle** [comment]
I still encounter this problem.
Linux Mint 19 with leiningen executable under `/usr/bin/lein`. Repl works when started from shell.
I tried `/usr/bin` as well as `/usr/bin/lein` as lein path setting but get 
_`Error starting repl: Error: spawn lein ENOENT`_
Leiningen 2.8.1 on Java 1.8.0_181 OpenJDK 64-Bit Server VM
Clojure 1.9.0
The Atom is latest stable v1.80 (i tried flathub.org)

[SOLVED] The Flatpak version of Atom does not have access to `spawn` so starting the repl as child process fails. Installed via official package sources.
