### ISSUE TITLE
Clicking 'Run all tests' does nothing if the ink console is focused

### ISSUE THREAD

**Issue by moxaj** [jasongilman/proto-repl#142]
This is just a minor bug. If I click the 'Run all tests' (speedometer icon) on the toolbar, the ink console input widget flickers but nothing happens.

**Comment by carocad** [comment]
@moxaj run all test requires a file from which to fetch the tests from. If you focus on the ink console then there are is no clojure file from which to fetch the test.
I guess that a simple error message indicating that would be enough to make the user realize the problem.

**Comment by moxaj** [comment]
It does not seem like it requires a file though. If I normally run it, it runs all tests from all namespaces related to my project (including the test namespaces from my dependencies).

Edit: is this the desired behaviour by the way? I'm not sure if i'm interested in the results of the tests defined in `clojure.tools.reader.impl.utils` ... If this is a quirk of `clojure.test/run-all-tests`, then maybe we should use `(clojure.test/run-tests & namespaces)`?

**Comment by carocad** [comment]
it seems like I overlooked that.

Which means that we are both right and that's a problem (in this case jeje).
[Here](https://github.com/jasongilman/proto-repl/blob/master/lib/proto-repl.coffee#L567-L573) is the code for 'run all test'. Which as I said requires _atom_ to have the focus on a file, but it also call `clojure.test/run-all-tests` just as you said.

Those two things are quite contradictory since there should be no need for a file if all files are being tested.

@jasongilman should be the one making the call for this behavior as I am not sure in which directions would he want to direct it, i.e. test only the file on focus?, test all the files on the project? leave it like that?

**Comment by jasongilman** [comment]
The goal of the Run All Tests button is to run all the tests in your project so this is indeed a bug. I'm looking into it now.

**Comment by moxaj** [comment]
Worry not! I have a PR ready.

**Comment by jasongilman** [comment]
@moxaj Oh, Sorry, I just saw your comment. Thank you for looking into it as well.
