### ISSUE TITLE
When `java.` is typed into REPL, a java program is started and then the REPL crashes

### ISSUE THREAD

**Issue by mnewt** [jasongilman/proto-repl#177]
When I type:

```clj
(java.
```

into the REPL, something (presumably tied to autocomplete) starts a blank java application with a title of "main". Then "REPL Closed" is printed in the REPL window and the REPL exits.

Can you reproduce this?

**Comment by jasongilman** [comment]
I can reproduce that. Though the REPL doesn't exit until you close the window. Here's what I think is happening. Proto REPL uses compliment as the completion provider. When compliment looks up the available candidates for completion some of that code is java.awt code which is used for creating Java GUIs. When that code is loaded it causes the current Java process to elevate to a different kind of process capable of displaying things. I'm fuzzy on exactly how this works within the java process. 

This does not start a new process. You can examine the java processes before and after and see that there are no new ones running. It just makes the current one more visible as this blank application called main. That's why when you close it it terminates the repl. 

You can try for yourself this code below.

This creates completions for java.awt and causes the "elevation" to a more visible process.

```
(do
 (require 'compliment.core)
 (let [completions (compliment.core/completions
                    "java.awt"
                    {:tag-candidates true
                     :ns 'java.awt
                     :context ""})]
   (->> completions
        (take 50)
        (mapv #(assoc % :docs (compliment.core/documentation
                               (:candidate %) 'java.awt))))))
```

This creates completions for java.lang which does not cause any visible change

```
(do
 (require 'compliment.core)
 (let [completions (compliment.core/completions
                    "java.lang"
                    {:tag-candidates true
                     :ns 'java.lang
                     :context ""})]
   (->> completions
        (take 50)
        (mapv #(assoc % :docs (compliment.core/documentation
                               (:candidate %) 'java.lang))))))
```

You can avoid the exiting REPL problem by avoiding the closing the "main" titled application that appears. There isn't much that I can do to prevent this behavior. It's based more on how the underlying JVM works.

**Comment by mnewt** [comment]
Many thanks for the detailed explanation, and also for proto-repl!
