### ISSUE TITLE
<unknown> is deprecated.

### ISSUE THREAD

**Issue by condur** [jasongilman/proto-repl#220]
Please update to the latest tool-bar provider service.
```
<unknown> (/Users/dima_condur/.atom/packages/tool-bar/lib/tool-bar.js:41:10)
Object.consumeToolbar (/Users/dima_condur/.atom/packages/proto-repl/lib/proto-repl.coffee:279:22)
Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:29:52)
ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:30:20)
Package.activateServices (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:369:71)
Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:194:16)
```

**Comment by joelrealubit** [comment]
**Prerequisites**
[x]  Put an X between the brackets on this line if you have done all of the following:
o	Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
o	Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
o	Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
o	Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
o	Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages
**Description**
The following appears under Deprecation Cop Pane: 
> Please update to the latest tool-bar provider service.
> Report Issue
> <unknown> - C:\Users\xxx\.atom\packages\tool-bar\lib\tool-bar.js:41:10
> Object.consumeToolbar - C:\Users\xxx\.atom\packages\proto-repl\lib\proto-repl.coffee:279:22
> Provider.provide - C:\Users\xxx\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\service-hub\lib\provider.js:29:52
> ServiceHub.provide - C:\Users\xxx\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\service-hub\lib\service-hub.js:30:20
> Package.activateServices - C:\Users\xxx\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package.js:369:71
> Package.activateNow - C:\Users\xxx\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package.js:194:16

**Steps to Reproduce**
Open Atom, click on the “n Deprecations” prompt at the bottom right, where n is 5 in my case. You will find the aforementioned error message displayed for proto-repl.

**Expected behavior:** no deprecation alerts for proto-repl
**Actual behavior:** that alert appears with the error message above.
**Reproduces how often:** 100%
**Versions**
Atom 1.13.0
proto-repl 1.4.12
Windows 10 Home
I set up atom the same way as described here: https://gist.github.com/jasongilman/d1f70507bed021b48625

**Additional Information**
n/a
