### ISSUE TITLE
REPL displays namespace-qualified hash maps without their namespace

### ISSUE THREAD

**Issue by seancorfield** [jasongilman/proto-repl#243]
Evaluate the following in ProtoREPL (in any Clojure REPL):

    {:a/b 1}

Expected (Clojure 1.9):

    #:a{:b 1}

Actual (Clojure 1.9):

    {:b 1}

The namespace qualifier just disappears.

**Comment by naartjie** [comment]
Is it an issue with the underlying eval runtime, which would mean this is related to issues with output of maps with ordered keys #192?

**Comment by jasongilman** [comment]
The result returned by nREPL is `#:a{:b 1}`. Proto REPL uses ClojureScript for some of the parsing code that runs in Atom.  It seems like ClojureScript isn't parsing that into the same value. If I run `(pr-str (cljs.reader/read-string "#:a{:b 1}"))` it returns `{:b 1}`.

I *think* that this is caused by http://dev.clojure.org/jira/browse/CLJS-1706. Until that is fixed it's going to be difficult to fix this completely. That said I have put in a work around so that the original string returned from the REPL will be used for display.

**Comment by seancorfield** [comment]
Wow, I'm kinda shocked that ClojureScript is so far behind on the namespaced-maps stuff, given all the work that's been done porting `clojure.spec` across!

**Comment by seancorfield** [comment]
That update is a slight improvement, but only for inline evaluation:

[Inline eval of `{:c/d 1}` shows namespace prefix](https://www.dropbox.com/s/c438xp3e3bdflqd/Screenshot%202017-04-15%2018.14.32.png?dl=0)

[REPL evaluation of `{:a/b 1}` does not](https://www.dropbox.com/s/506rxmp594fgjkk/Screenshot%202017-04-15%2018.15.31.png?dl=0)

Is that expected with that update? Is there no way to display the actual result from nREPL?

**Comment by jasongilman** [comment]
Do you have pretty printing turned on? If you turn it off you'll see the correct value. The auto pretty printing is using ClojureScript and Fipp so it will have the same problem.

**Comment by seancorfield** [comment]
Ah yes, that did indeed fix it. What side effects will I get from disabling that?

**Comment by jasongilman** [comment]
You won't get automatically pretty printed results at the REPL. This is actually the setting that I use. You can still pretty print the results by sending the pretty print command after executing something. That will pretty print correctly because it uses clojure.pprint/pp through the REPL. See the keybinding documentation for the keystroke.
