### ISSUE TITLE
Enhancement: Echo evaluated text in the REPL pane

### ISSUE THREAD

**Issue by IshmaelYavitz** [jasongilman/proto-repl#26]
I write Clojure in files open in the editor and use proto-repl to evaluate things in those files via `proto-repl:execute-block` and `proto-repl:execute-selected-text`.

As it stands, the output is very confusing.  The evaluated text isn't written to the REPL window, and the _result_ is written after the prompt (e.g. `user=>`).

In other words, the evaluated text isn't written at all and the result is written where the evaluated text would go if you were using a REPL.

It would make the output pane more useful if the evaluated text were echoed to it.

**Comment by IshmaelYavitz** [comment]
Also, since evaluated expressions aren't written to the REPL window, when looking at it, there's no way to tell what output came from what expressions.

**Comment by jasongilman** [comment]
I personally don't want the output shown (most of the time) based on the way that I work (the code I executed was in a scratch file) but I think you're right.  I'm going to display the code that was executed in the REPL with an option to turn it off. It will be on by default because I think this is better for most people. I'm working on major modifications to the REPL text editor area as part of #24. This will be part of that change.

**Comment by IshmaelYavitz** [comment]
Awesome, thanks!

**Comment by jasongilman** [comment]
This feature has been implemented in 0.9.0
