### ISSUE TITLE
Proto REPL just opens Java Window - Didn't used too

### ISSUE THREAD

**Issue by broliverparker** [jasongilman/proto-repl#300]
Hi, I recently updated the proto-repl extension inside Atom and before hand everything seemed to work. The repl started inside atom and I could select clojure code to run without any problems. However after the update whenever I try and run the REPL i just get a java window loading up saying i've started the REPL server but I can't do anything in ATOM. Using shift + enter doesn't work and I cant use the hotkeys to select clojure code without getting the error: "This command requires you to position the cursor on a Clojure var."
 
Image below is the java window that appears, I can't seem to do anything in that either. Didn't have these issues before with my program so I don't think its related to that. Any idea? Thanks!

![image](https://user-images.githubusercontent.com/11505007/37977572-e28b6396-31db-11e8-8be1-016f7df298b7.png)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/2912230/38436648-c4ccaf0c-3a07-11e8-8256-40051a553807.png)
The same problem :(

**Comment by thomasiffland** [comment]
Same issue

**Comment by sashton** [comment]
@broliverparker @tonic4401 @thomasiffland It appears my attempts to kill the REPL JVM in https://github.com/jasongilman/proto-repl/pull/292 didn't work for Windows (I didn't have a Windows install at the time to test). I've since got access to a Windows env and submitted a fix for the issue you are seeing: https://github.com/jasongilman/proto-repl/pull/303 

If you are able to, it would be great if you could try that fix out to make sure your problem is resolved.

**Comment by thomasiffland** [comment]
This fixed the issue for me, thank you!
