### ISSUE TITLE
Key binding prefix is already taken so shortcuts don't work (Windows)

### ISSUE THREAD

**Issue by asampal** [jasongilman/proto-repl#56]
On Windows (not sure about other platforms), `Ctrl+,` is already the key binding for showing Atom settings so trying to invoke the default proto-repl shortcuts doesn't work. I'm not sure this is the ideal choice of prefix for a plugin, but maybe you have a good reason for going with that.

**Comment by jasongilman** [comment]
Thanks for letting me know. Picking good key bindings is tricky and I've obviously chosen the wrong ones in this case. I based them off what Sublime REPL was using. I'm going to start looking into solutions for this. If you have any suggestions for what to use please comment here.

**Comment by asampal** [comment]
Not sure I have a good suggestion so for now I just remapped the settings binding.

**Comment by jasongilman** [comment]
I did some looking into the keybindings. The current keybindings would be a problem for Linux users as well. I'd like to keep them very close to the current one since people may be building up muscle memory. Here are some potential ones I rejected:
- `ctrl-shift-,` This is actually ctrl-< and is already bound to something.
- `ctrl-.` (period is next to comma). This brings up the Keybinding Resolver on windows and linux.
- `ctrl-/` (/ is close to comma) Already bound to comment code.
- `ctrl-space` - This may be already bound to application launchers.

I'm leaning towards making the keybindings `ctrl-alt-,` for windows and linux users and leaving it as `ctrl-,` for mac users. Do you have any opinion on that as a Windows user?

**Comment by asampal** [comment]
I'm fine with things as they are, actually. Changing the binding for settings isn't a big deal. Opening this issue was mostly to point out that there was a conflict. What I did is remap the Settings binding in the user keymap to `ctrl-alt-;` (for both `application:show-settings` and `settings-view:open`) and this lets me use `ctrl-,` as a prefix for the proto-repl commands. Interestingly, I can still use `ctrl-,` for settings (which appears after a slight delay) if I just don't follow that by the secondary key in your bindings. I guess it's just the result of how Atom falls through the various bindings. So, really, in this way I can still use the original binding for settings and the proto-repl ones.

**Comment by jasongilman** [comment]
I tried the keybindings for a bit with it set to cmd-, so I could see what it was like. It works like you describe it and only introduces a slight delay when opening settings. I'm going to close the issue for now but will consider reopening it if anyone else finds this is a problem.

**Comment by jasongilman** [comment]
Reopening this based on feedback from users in https://github.com/jasongilman/proto-repl-demo/issues/7
