### ISSUE TITLE
Interoperate with Boot in addition to Leiningen

### ISSUE THREAD

**Issue by phreed** [jasongilman/proto-repl#71]
I presently have a project.clj in addition to build.boot and this works but...
It would be nice to have proto-repl interoperate with boot, http://boot-clj.com/ , just like with leiningen.
If you do not have time to work on this could you provide some direction on where the leiningen related code lives?
I could work on this in a fork.

**Comment by jasongilman** [comment]
I don't think this would be that hard to implement. These files would need to be updated:

https://github.com/jasongilman/proto-repl/blob/master/lib/local-repl-process.coffee
https://github.com/jasongilman/proto-repl/blob/master/lib/lein-runner.coffee

The latter should probably be renamed so it's not lein specific. That might be the only changes required. You can take a try at updating it. If it looks too tricky I don't mind making the change as one of the next things I work on.

**Comment by phreed** [comment]
You are correct, in fact the system can already use boot.
I was able to get proto-repl to use boot simply by changing the proto-repl settings.
Specifically, changing 'Lein Path' to '/usr/local/bin/boot' , 'Lein Args' to 'repl' and
adding a 'build.boot' file alongside the project.clj did the trick.
Then 'Packages>proto-repl>Start REPL from open project.clj' did the trick.
The project.clj file needs to left where it is to indicate the project folder.

I tested this with your proto-repl-demo project and added the following file.
[build.boot.txt](https://github.com/jasongilman/proto-repl/files/159222/build.boot.txt)

The changes suggested are:
1) change properties names related to leiningen to be generic build-tool arguments.
2) identify the project directory by the presence of the build file, either project.clj or build.boot.
    The build file name could be an argument
3) update the documentation

**Comment by phreed** [comment]
When running the commands from autoeval.clj in proto-repl-demo the prc command fails.
CompilerException java.lang.RuntimeException: No such namespace: prc, compiling: (/tmp/boot.user###.clj:1:1)
This is only a problem when starting the repl with boot.
There is no problem when starting with leiningen.
What am I missing?

**Comment by jasongilman** [comment]
I think you're missing a dependency on proto-repl-charts. Take a look at the dependencies in the project.clj https://github.com/jasongilman/proto-repl-demo/blob/master/project.clj#L8

**Comment by jasongilman** [comment]
I found one of the issues is that the user namespace is different with boot and user. I'm fixing that now.

**Comment by jasongilman** [comment]
I was able to fix some of the issues. Could you checkout master of proto-repl and proto-repl-demo and make sure it works the way you expect with boot? If it looks good then I'll do another release.

**Comment by phreed** [comment]
I will check it out later tonight.

**Comment by jasongilman** [comment]
I went ahead and released this. Please reopen if there are issues or file a new issue.

**Comment by phreed** [comment]
I am still having problems (possibly a user error).
When trying to run "prc/line-chart" I still get the same error as above.
Is 'prc' an alias for a namespace?
If so what is the namespace?
Oh, I see it is brought in with the 'user.clj'

**Comment by jasongilman** [comment]
`prc` stands for proto-repl-charts. It's not an alias. I used that for the namespace so that it would always be easy to reference it. Perhaps I should have used a longer namespace for that. If you have the latest proto-repl package and proto-repl-demo then it should work. I added an option in the latest proto-repl for whether you preferred lein or not. Make sure that's unchecked and try starting the REPL.  

I just updated the Boot instructions in proto-repl-demo. https://github.com/jasongilman/proto-repl-demo/blob/master/demos.md#demo-start-the-repl-with-boot 

Give those a try. I just realized that the `prc` namespace may also not be loaded because you haven't refreshed yet. Try that after starting the REPL to see if it resolves issues. I recommend updating the setting to automatically refresh on REPL start. See the refresh instructions here: https://github.com/jasongilman/proto-repl-demo/blob/master/demos.md#demo-refresh-all-code-in-the-project
