### ISSUE TITLE
Starting repl / refreshing namespaces fails with :aot compiler option

### ISSUE THREAD

**Issue by nimaai** [jasongilman/proto-repl#88]
Hello, 

I am working on https://github.com/madek/madek-api. If I start the proto-repl for this project or refresh the namespaces, then I get an error:

`:error-while-loading madek.api.resources.groups.index`

Starting the repl from terminal has no problems.

I am using `lein` on Mac OSX installed using homebrew (v2.6.1).

Thanks,
Matúš

**Comment by nimaai** [comment]
I have found where the problem lies, namely the `:aot` compiler option in `project.clj` is responsible for it. If I remove it, then the starting of repl and code refreshing works fine.

**Comment by jasongilman** [comment]
The aot issue when working at the REPL is a known Clojure problem (but not a Clojure bug). My understanding is that when you have :aot at the top level like in [your project.clj](https://github.com/Madek/madek-api/blob/master/project.clj#L34) it will ahead-of-time compile the code into class files when the REPL is run (or pretty much any lein command is run). This messes with code reloading in the REPL because the pre-compiled code is already in the classpath. The solutions is to limit :aot to a specific profile when you're building a jar for deployment. The [Leiningen sample project.clj has an example of this.](https://github.com/technomancy/leiningen/blob/master/sample.project.clj#L163). If you add a profile for aot that will solve the problem. 

One thing to remember is anytime after AOT has been run and class files are generated you need to clean them out with a `lein clean` before you start the REPL. See [clojure tools.namespace potential problems](https://github.com/clojure/tools.namespace#warnings-and-potential-problems) for more information about this. 

Closing this issue since it isn't a Proto REPL problem.
